export const mockData = {
  users_tbl: [
    {
      user_id: 1,
      role: 'seller',
      shop_name: 'Food Corner',
      shop_tagline: 'Food ng bayan',
      logo: 'pizza1.png',
    },
    {
      user_id: 6,
      role: 'seller',
      shop_name: "Egg's Shop",
      shop_tagline: 'Delicious Foods',
      logo: 'dessert1.png',
    },
    {
      user_id: 10,
      role: 'buyer',
      full_name: 'Gusion Dela Cruz',
    },
  ],
  category_tbl: [
    { category_id: 1, category_name: 'Pizza', icon_name: 'local_pizza' },
    { category_id: 2, category_name: 'Beverage', icon_name: 'local_cafe' },
    { category_id: 3, category_name: 'Salad', icon_name: 'fork_spoon' },
    { category_id: 4, category_name: 'Pasta', icon_name: 'dinner_dining' },
    { category_id: 5, category_name: 'Dessert', icon_name: 'icecream' },
  ],
  product_tbl: [
    {
      product_id: 1,
      category_id: 1,
      product_name: 'Vegetarian Pizza',
      product_desc: 'Vegetariaan Pizza Vegetarian Pizza',
      product_img: 'pizza1.png',
      price: 175.0,
      avail_stocks: 12,
      seller_id: 1,
    },
    {
      product_id: 50,
      category_id: 1,
      product_name: 'Margherita Pizza',
      product_desc: 'A classic delight with fresh tomatoes and basil',
      product_img: 'pizza5.png',
      price: 175.0,
      avail_stocks: 12,
      seller_id: 1,
    },
    {
      product_id: 51,
      category_id: 1,
      product_name: 'Neapolitan Pizza',
      product_desc: 'A traditional pizza with a thin crust and simple toppings',
      product_img: 'pizza6.png',
      price: 105.0,
      avail_stocks: 12,
      seller_id: 1,
    },
    {
      product_id: 52,
      category_id: 1,
      product_name: 'Vegetarian Pizza',
      product_desc: 'A delightful pizza loaded with fresh vegetables',
      product_img: 'pizza7.png',
      price: 145.0,
      avail_stocks: 12,
      seller_id: 1,
    },
    {
      product_id: 5,
      category_id: 5,
      product_name: 'Tiramisu Cake',
      product_desc: 'A classic Italian dessert made with coffee-soaked ladyfingers and mascarpone cheese.',
      product_img: 'TiramisuCake.png',
      price: 100.0,
      avail_stocks: 8,
      seller_id: 1,
    },
    {
      product_id: 7,
      category_id: 1,
      product_name: 'Pepperoni Pizza',
      product_desc: 'Pepperoni Pizza Pepperoni Pizza',
      product_img: 'pizza3.png',
      price: 200.0,
      avail_stocks: 6,
      seller_id: 1,
    },
    {
      product_id: 14,
      category_id: 5,
      product_name: 'Blackberry Pie',
      product_desc: 'A delicious pie filled with fresh blackberries.',
      product_img: 'BlackberryPie.png',
      price: 100.0,
      avail_stocks: 14,
      seller_id: 1,
    },
     {
      product_id: 14,
      category_id: 5,
      product_name: 'Belgian Waffle',
      product_desc: 'A delicious waffle topped with fresh berries and whipped cream.',
      product_img: 'BelgianWaffle.png',
      price: 100.0,
      avail_stocks: 14,
      seller_id: 1,
    },
     {
      product_id: 14,
      category_id: 5,
      product_name: 'Ice Cream',
      product_desc: 'A creamy ice cream dessert in a plate.',
      product_img: 'IceCream.png',
      price: 100.0,
      avail_stocks: 14,
      seller_id: 1,
    },
    {
      product_id: 17,
      category_id: 2,
      product_name: 'Lemon Tea',
      product_desc: 'A refreshing lemon-flavored tea beverage',
      product_img: 'LemonTea.png',
      price: 85.0,
      avail_stocks: 24,
      seller_id: 1,
    },
    {
      product_id: 17,
      category_id: 2,
      product_name: 'Caramel Coffee',
      product_desc: 'A rich and creamy coffee beverage with caramel flavor',
      product_img: 'CaramelCoffee.png',
      price: 85.0,
      avail_stocks: 24,
      seller_id: 1,
    },
    {
      product_id: 17,
      category_id: 2,
      product_name: 'Hot Choco',
      product_desc: 'A warm and comforting hot chocolate drink',
      product_img: 'HotChoco.png',
      price: 85.0,
      avail_stocks: 24,
      seller_id: 1,
    },
    {
      product_id: 17,
      category_id: 2,
      product_name: 'Hot Cappuccino',
      product_desc: 'A rich and creamy cappuccino with a velvety foam',
      product_img: 'HotCappuccino.png',
      price: 85.0,
      avail_stocks: 24,
      seller_id: 1,
    },
    {
      product_id: 22,
      category_id: 4,
      product_name: 'Trenette Pesto',
      product_desc: 'Classic Ligurian pasta tossed with vibrant basil pesto and a touch of olive oil',
      product_img: 'TrenettePesto.png',
      price: 140.0,
      avail_stocks: 5,
      seller_id: 6,
    },

    {
      product_id: 301,
      category_id: 4,
      product_name: 'Pasta Carbonara',
      product_desc: 'Creamy pasta with eggs, cheese, and crispy bacon for rich, savory flavor',
      product_img: 'PastaCarbonara.png',
      price: 120.0,
      avail_stocks: 5,
      seller_id: 6,
    },

    {
      product_id: 303,
      category_id: 4,
      product_name: 'Spaghetti Twist',
      product_desc: 'Twirled Spaghetti served with a savory sauce for a classic, comforting meal',
      product_img: 'SpaghettiTwist.png',
      price: 120.0,
      avail_stocks: 5,
      seller_id: 6,
    },

    {
      product_id: 304,
      category_id: 4,
      product_name: 'Tuna Pasta',
      product_desc: 'Tender Pasta mixed with flaky tuna and a light, flavorful sauce',
      product_img: 'TunaPasta.png',
      price: 120.0,
      avail_stocks: 5,
      seller_id: 6,
    },

    {
      product_id: 60,
      category_id: 3,
      product_name: 'Tofu Salad',
      product_desc: 'A fresh mix of tofu, crisp veggies, and light dressing for a healthy, flavorful bite.',
      product_img: 'TofuSalad.png',
      price: 199.0,
      avail_stocks: 19,
      seller_id: 6,
    },
    {
      product_id: 61,
      category_id: 3,
      product_name: 'Tuna Salad',
      product_desc: 'A hearty blend of tuna, crisp veggies, and creamy dressing for a fresh, savory taste',
      product_img: 'TunaSalad.png',
      price: 199.0,
      avail_stocks: 25,
      seller_id: 6,
    },

    {
      product_id: 62,
      category_id: 3,
      product_name: 'Vegetable Salad',
      product_desc: 'A colorful mix of fresh veggies tossed in a light, zesty dressing',
      product_img: 'VegetableSalad.png',
      price: 160.0,
      avail_stocks: 15,
      seller_id: 6,
    },

    {
      product_id: 63,
      category_id: 3,
      product_name: 'Caesar Salad',
      product_desc: 'Crisp romaine, creamy dressing, and crunchy croutons topped with parmesan',
      product_img: 'CaesarSalad.png',
      price: 180.0,
      avail_stocks: 15,
      seller_id: 6,
    },
  ],
  cart_tbl: [{ cart_id: 10, user_id: 10 }],
  cart_items_tbl: [
    { cart_item_id: 1, cart_id: 10, product_id: 1, quantity: 2 },
    { cart_item_id: 2, cart_id: 10, product_id: 60, quantity: 1 },
    { cart_item_id: 3, cart_id: 10, product_id: 14, quantity: 3 },
  ],
  orders_tbl: [
    { order_id: 16, buyer_id: 10, status: 'pending', total_price: 199.0, ordered_at: '2025-05-05T21:35:01' },
    { order_id: 19, buyer_id: 10, status: 'completed', total_price: 1200.0, ordered_at: '2025-05-06T05:20:23' },
  ],
  order_items_tbl: [
    { order_items_id: 39, order_id: 16, product_id: 60, quantity: 1, price_each: 199.0 },
    { order_items_id: 44, order_id: 19, product_id: 59, quantity: 12, price_each: 100.0 },
  ],
  order_seller_tbl: [
    { id: 3, order_id: 16, seller_id: 6, status: 'completed' },
    { id: 6, order_id: 19, seller_id: 6, status: 'completed' },
  ],
  analytics: {
    topProducts: [
      { product_id: 7, product_name: 'Pepperoni Pizza', total_sold: 145 },
      { product_id: 50, product_name: 'Margherita Pizza', total_sold: 112 },
      { product_id: 5, product_name: 'Tiramisu Cake', total_sold: 96 },
      { product_id: 59, product_name: 'Hot Chocolate', total_sold: 88 },
    ],
    topCategories: [
      { category_id: 1, category_name: 'Pizza', total_revenue: 48500 },
      { category_id: 5, category_name: 'Dessert', total_revenue: 28100 },
      { category_id: 2, category_name: 'Beverage', total_revenue: 22440 },
      { category_id: 4, category_name: 'Pasta', total_revenue: 18960 },
    ],
    topCustomers: [
      { user_id: 10, full_name: 'Gusion Dela Cruz', total_spent: 1245.0 },
      { user_id: 11, full_name: 'Layla Santos', total_spent: 980.0 },
      { user_id: 12, full_name: 'Claude Ramirez', total_spent: 865.0 },
    ],
    combos: [
      {
        combo_id: 1,
        product1_id: 7,
        product1_name: 'Pepperoni Pizza',
        product2_id: 17,
        product2_name: 'Lemon Tea',
        count: 62,
      },
      {
        combo_id: 2,
        product1_id: 1,
        product1_name: 'Vegetarian Pizza',
        product2_id: 59,
        product2_name: 'Hot Chocolate',
        count: 51,
      },
      {
        combo_id: 3,
        product1_id: 50,
        product1_name: 'Margherita Pizza',
        product2_id: 60,
        product2_name: 'Tofu Salad',
        count: 44,
      },
      {
        combo_id: 4,
        product1_id: 5,
        product1_name: 'Tiramisu Cake',
        product2_id: 14,
        product2_name: 'Blackberry Pie',
        count: 39,
      },
    ],
    recentOrders: [
      {
        order_id: 201,
        buyer_id: 10,
        full_name: 'Gusion Dela Cruz',
        product_id: 7,
        product_name: 'Pepperoni Pizza',
        product_img: 'pizza3.png',
        quantity: 2,
        ordered_at: '2025-05-06T07:15:00',
      },
      {
        order_id: 202,
        buyer_id: 11,
        full_name: 'Layla Santos',
        product_id: 59,
        product_name: 'Hot Chocolate',
        product_img: 'HotChoco.png',
        quantity: 3,
        ordered_at: '2025-05-06T06:52:00',
      },
      {
        order_id: 203,
        buyer_id: 12,
        full_name: 'Claude Ramirez',
        product_id: 60,
        product_name: 'Tofu Salad',
        product_img: 'TofuSalad.png',
        quantity: 1,
        ordered_at: '2025-05-06T06:10:00',
      },
      {
        order_id: 204,
        buyer_id: 10,
        full_name: 'Gusion Dela Cruz',
        product_id: 5,
        product_name: 'Tiramisu Cake',
        product_img: 'TiramisuCake.png',
        quantity: 1,
        ordered_at: '2025-05-06T05:45:00',
      },
    ],
  },
};
